---
jobs:
  - name: unit-1.9
    public: true
    serial: true
    plan:
      - get: bosh-src
        trigger: true
      - task: test
        file: bosh-src/ci/concourse/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 1.9.3

  - name: unit-2.1
    public: true
    serial: true
    plan:
      - get: bosh-src
        trigger: true
      - task: test
        file: bosh-src/ci/concourse/tasks/test-unit-coverage.yml
        config:
          params:
            RUBY_VERSION: 2.1.6
            CODECLIMATE_REPO_TOKEN: {{codeclimate_token}}

  - name: integration-mysql-1.9
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-1.9, unit-2.1]
        trigger: true
      - task: test
        privileged: true
        file: bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 1.9.3

  - name: integration-mysql-2.1
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-1.9, unit-2.1]
        trigger: true
      - task: test
        privileged: true
        file: bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 2.1.6

  - name: integration-postgres-1.9
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-1.9, unit-2.1]
        trigger: true
      - task: test
        privileged: true
        file:  bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 1.9.3

  - name: integration-postgres-2.1
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-1.9, unit-2.1]
        trigger: true
      - task: test
        privileged: true
        file: bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 2.1.6

resources:
  - name: bosh-src
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh.git
      branch: global-net
